version: '3.8'
services:
  db:
    image: mysql
    container_name: blogapi-db
    restart: always
    environment:
      MYSQL_DATABASE: 'blogapi'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    networks:
      - blogapi-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  application:
    image: adoptopenjdk/openjdk11:alpine-jre
    container_name: blogapi-application
    volumes:
      - "./target/blogapi-0.0.1-SNAPSHOT.jar:/blogapi-0.0.1-SNAPSHOT.jar:rw"
    ports:
      - "8080:8080"
    networks:
      - blogapi-network
    depends_on:
      - "db"
    command: ["java","-jar","/blogapi-0.0.1-SNAPSHOT.jar"]
networks:
  blogapi-network:
    name: blogapi-network
    driver: bridge
